### PR TITLE
Fixed xevil build to work with raspberry pi

### LINKED ISSUE #1: Add support for Raspberry Pi
Currently there is no build option for ARM

### PR DESCRIPTION
**Pull request by ameliabradley**
Closes #1

### CODE REVIEW

**Comment by ameliabradley** [comment]
Install prerequisites:

`sudo apt install libx11-dev libxpm-dev xfonts-base`

Build:

`HOSTNAME=arm make`

**Comment by ameliabradley** [comment]
Eh... also, I had to replace the default font 8x13bold with 6x13. I'm not sure why it wasn't there.

File: cmn/game.cpp [hunk 1]
```diff
@@ -580,7 +580,7 @@ void GameObjects::level_reset(const Dim &worldDim,GameStyleP style) {
     for (n = 0; n < oItemsNum; n++) {
       // Check not already set.
       assert(maximums[oItems[n]->classId] == 0);
-      float objWPercent = (float)max(oItems[n]->objectWorldPercent,
+      float objWPercent = (float)fmax(oItems[n]->objectWorldPercent,
```
Comment (lvella) [inline cmn/game.cpp:583]: Why have you used `fmax` instead of `std::max<float>` here, but used `std::max` in the other place?
